# Generated by Django 3.0.7 on 2020-11-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20201104_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.ShippingAddress'),
        ),
    ]
